name: eye_wise_connect
description: AI-powered eye diagnosis and health assistant app
publish_to: 'none'
version: 2025.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Image Handling
  image_picker: ^1.0.4
  image: ^4.1.3
  tflite_flutter: ^0.10.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Speech Recognition & Text-to-Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Camera
  camera: ^0.10.5+5
  
  # File Handling
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  
  # UI Enhancements
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Charts
  fl_chart: ^0.65.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Utils
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  
  # AI Chatbot
  google_generative_ai: ^0.4.7

  # Voice Recording & Playback
  record: ^5.0.4
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/l10n/
    - assets/chatbot/
    - assets/models/
  
  generate: true
  

