import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:record/record.dart';
import '../services/voice_chat_service.dart';

class HuaweiSisProvider with ChangeNotifier {
  final AudioRecorder _recorder = AudioRecorder();
  final VoiceChatService _service;
  bool _isRecording = false;
  bool _isSending = false;
  String _transcript = '';
  String _botReply = '';
  String? _error;

  HuaweiSisProvider({
    required VoiceChatService service,
  }) : _service = service;

  bool get isRecording => _isRecording;
  bool get isSending => _isSending;
  String get transcript => _transcript;
  String get botReply => _botReply;
  String? get error => _error;

  /// Start recording audio
  Future<void> startRecording() async {
    if (_isRecording || _isSending) return;

    try {
      setState(() {
        _error = null;
        _transcript = '';
        _botReply = '';
      });

      // Request permission
      if (!await _recorder.hasPermission()) {
        throw Exception('Microphone permission denied');
      }

      // Start recording to file with WAV format (16kHz, mono)
      // Note: path will be auto-generated by the recorder
      await _recorder.start(
        const RecordConfig(
          encoder: AudioEncoder.wav,
          sampleRate: 16000,
          numChannels: 1,
        ),
        path: '', // Empty path = auto-generate
      );

      setState(() {
        _isRecording = true;
      });
    } catch (e) {
      setState(() {
        _isRecording = false;
        _error = e.toString();
      });
    }
  }

  /// Stop recording and send to backend for processing
  Future<void> stopAndSend() async {
    if (!_isRecording) return;

    try {
      setState(() {
        _isRecording = false;
        _isSending = true;
      });

      // Stop recording and get file path
      final path = await _recorder.stop();
      
      if (path == null) {
        throw Exception('Recording failed - no audio file');
      }

      // Read audio file bytes
      final file = File(path);
      final audioBytes = await file.readAsBytes();

      // Send to backend
      final result = await _service.sendVoiceMessage(audioBytes);

      setState(() {
        _transcript = result['userText'] ?? '';
        _botReply = result['botReply'] ?? '';
        _isSending = false;
      });

      // Clean up audio file
      try {
        await file.delete();
      } catch (e) {
        debugPrint('Failed to delete audio file: $e');
      }
    } catch (e) {
      debugPrint('Error in stopAndSend: $e');
      setState(() {
        _isSending = false;
        _error = e.toString();
      });
    }
  }

  /// Backward compatibility: alias for startRecording
  Future<void> startListening() async {
    await startRecording();
  }

  /// Backward compatibility: alias for stopAndSend
  Future<void> stopListening() async {
    await stopAndSend();
  }

  /// Cancel recording without sending
  Future<void> cancelRecording() async {
    if (!_isRecording) return;

    try {
      final path = await _recorder.stop();
      
      setState(() {
        _isRecording = false;
      });

      // Clean up audio file if it exists
      if (path != null) {
        try {
          await File(path).delete();
        } catch (e) {
          debugPrint('Failed to delete audio file: $e');
        }
      }
    } catch (e) {
      debugPrint('Error canceling recording: $e');
      setState(() {
        _isRecording = false;
        _error = e.toString();
      });
    }
  }

  void setState(VoidCallback fn) {
    fn();
    notifyListeners();
  }

  @override
  void dispose() {
    _recorder.dispose();
    super.dispose();
  }
}
